pipeline{
    agent any

    stages{
        stage('zip the file'){
            steps{
                sh 'zip ansible-${BUILD_ID}.zip * --exclude Jenkinsfile'
               }
            }
        }
        stage('upload artifacts to jfrog')
          steps{
                sh 'curl -uadmin:APB29Dhy6UpUNdnyKWtfmHidLbN -T \
                ansible-${BUILD_ID}.zip \
                "http://34.239.253.138:8081/artifactory/ansible/ansible-${BUILD_ID}.zip"'
            }
            }
