---
- hosts: all
  become: yes
  #gather_facts: no
  tasks: 
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family=="Debian"
    
    - name: Install nginx on redhat family
      package:
        name: httpd
        state: absent
      when: ansible_os_family=="RedHat"
   
    - name: Start httpd daemon
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family=="RedHat"
      
    - name: Create user Rita
      user: 
        name: Rita
        comment: Rita Asiedu
        shell: /bin/bash
    
    - name: Create group
      group:
        name: cloudteam
        state: present
   
    - name: create index file
      file:
        path: /var/www/html/index.html
        state: touch
    


    
    - name: create directory
      file:
        path: /tmp/os
        state: directory
   
    - name: copy content to index
      copy: 
        dest: /var/www/html/index.html
        content: 'This is created using ansible'
      
    